local hpv=require("hypervisor")
local thread=require("thread")
thread.create(function()
    coroutine.yield()
    coroutine.yield()
    coroutine.yield()
    sleep(3)
    coroutine.yield()
end, "e")
hpv.createProcessFromFile("/bin/shell","shell")
sleep(999999)