title: HyperionOS
description: Bookmark
plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
logo: "/assets/images/logo.png"
nav_external_links:
  - title: HyperionOS SRC
    url: https://github.com/Starlight-CC/hyperion-os
    opens_in_new_tab: true
